### ISSUE TITLE
Google Inbox plugin

### ISSUE THREAD

**Issue by xarg** [gorgias/gorgias-chrome#109]
By popular request make a Google Inbox plugin.

**Comment by RomainLapeyre** [comment]
+1

**Comment by RomainLapeyre** [comment]
+1

**Comment by RomainLapeyre** [comment]
Keyboard completion and CTRL+SPACE Work.

Need to add support variables + quick access button.

**Comment by RomainLapeyre** [comment]
+1

**Comment by RomainLapeyre** [comment]
+1

**Comment by luisherranz** [comment]
+1

**Comment by xarg** [comment]
+1

**Comment by RomainLapeyre** [comment]
+1

**Comment by RomainLapeyre** [comment]
@xarg what do you think of asking a freelancer to do it?

**Comment by xarg** [comment]
@ghinda can you please have a look at what can we do here? There is really lots of demand for this.

**Comment by ghinda** [comment]
Started work on the plugin for Google Inbox.

It's still very much wip. Will finish it up after the new year's.
Branch is `ghinda--googleinbox-suport`.

**Comment by xarg** [comment]
@ghinda seems there are some issues with Inbox still. For example the text sometimes goes outside of the edit area and stays there. See the gif below:
![screenflow](https://cloud.githubusercontent.com/assets/94721/23286901/43e79ce8-f9ef-11e6-91d4-c1c7d796af35.gif)


To reproduce this, I deleted all the text and then used the dialog. Seems like it loses focus from the editor and goes to the element on top of it.

Unrelated: Can we also add the little `g` button in the compose area?

**Comment by xarg** [comment]
Fixed in version 5.6.4
