### ISSUE TITLE
No sync of default templates can lead to duplicate templates

### ISSUE THREAD

**Issue by RomainLapeyre** [gorgias/gorgias-chrome#111]
Problem: you can have two templates with "kr" as a shortcut

Reproduce:
- Install the extension, you have Kind Regards as a default template, with "kr" as a shortcut
- Signup for Gorgias.io
- Create a template with "kr" as a shortcut
- Sync the extension
- You end up with 2 templates with "kr" as shortcuts, and can only use one.

Potential Solution: 
- Sync default templates from the extension to Gorgias.io

**Comment by xarg** [comment]
The synced templates should not be shared by default
