### ISSUE TITLE
Help in the Extension sidebar mails to "support@gorgias.io"

### ISSUE THREAD

**Issue by RomainLapeyre** [gorgias/gorgias-chrome#112]
## Goal
It seems people don't see the response to their support request in the Chrome Web Store support tab. 
We want to test getting back to email support to figure out whether it serves users better. 

## Expected behaviour
- Go to the Gorgias Extension
- Click on "help" in the side bar
- It mails to "support@gorgias.io"

**Comment by xarg** [comment]
I think that it's actually not a bad idea to leave this on. It makes the extension seem more active. Closing for now.
