### ISSUE TITLE
Can't open Gorgias page

### ISSUE THREAD

**Issue by RomainLapeyre** [gorgias/gorgias-chrome#113]
Problem: Can't open Gorgias page (e.g. chrome-extension://lmcngpkjkplipamgflhioabnhnopeabf/pages/bg.html#/list)

Reproduce : 
- Click on the "G" icon to open chrome-extension://lmcngpkjkplipamgflhioabnhnopeabf/pages/bg.html#/list
- On the same tab, navigate to another page from the navigation bar (e.g. google.com)
- Click on the "G" 
--> It goes back to the right tab, but you see google.com and not the Gorgias page

**Comment by xarg** [comment]
Can't reproduce this anymore. I did change the behaviour of opening so it could have been fixed.

Reopen if this is still occuring.
