### ISSUE TITLE
Attach files to template

### ISSUE THREAD

**Issue by RomainLapeyre** [gorgias/gorgias-chrome#122]
Provide the ability to attach files from:
- Google Drive

**Comment by xarg** [comment]
+1

**Comment by RomainLapeyre** [comment]
+1 "willing to pay for it"

**Comment by RomainLapeyre** [comment]
+1

**Comment by GFNX** [comment]
+1
Willing to pay

**Comment by RomainLapeyre** [comment]
+1

**Comment by ticruz38** [comment]
Hi
@xarg I have security concern about using FileStack API, in the examples, they want me to copy the 'private' api key either into our html input as data embedded, or in our client side javascript code...
They provide a policy system to avoid user updating too big files via our api key. that's all about security...
Unless I am missing something here, their API cannot be serious!

**Comment by RomainLapeyre** [comment]
+1, from Google Drive
