### ISSUE TITLE
Add an option for case sensitive search

### ISSUE THREAD

**Issue by RomainLapeyre** [gorgias/gorgias-chrome#123]
Add a parameter to have case sensitive search in the search dialog search box (and non case sensitive search where not enabled)

Should be disabled by default, so the search should be non case sensitive by default. Rationale: no search is case sensitive on Gorgias.io / gorgias-chrome

**Comment by RomainLapeyre** [comment]
@xarg, do you agree with the default being non case sensitive? It was asked by a customer and to me it makes total sense.

**Comment by RomainLapeyre** [comment]
+1

**Comment by RomainLapeyre** [comment]
+1

**Comment by xarg** [comment]
Agreed. By default case insensitive with the option in the Settings to use case sensitive search.
