### ISSUE TITLE
Make it easy to not share some templates

### ISSUE THREAD

**Issue by RomainLapeyre** [gorgias/gorgias-chrome#124]
Asked by chris@reefdigital.com.au

Currently, the flow to not share a template is: 
- Disable sharing by default
- Create your template
- Then you'll need to manually share templates if you'd like some of them to be shared. 

Some users would rather have 2 categories: public & private templates

Customer wanting this: Doctolib, chris@reefdigital.com.au

**Comment by xarg** [comment]
A solution to this could  be to show a checkbox that says: "This is a private template" - which is unchecked by default.  So  when you create a template you could choose if it's private or shared with everyone.

**Comment by xarg** [comment]
This should have been fixed.
