### ISSUE TITLE
chrome.storage.sync at first, then switch to chrome.storage.local when big

### ISSUE THREAD

**Issue by xarg** [gorgias/gorgias-chrome#134]
People are complaining that they lose their templates because they reinstall their OS or lose their computer. They don't know/care (or should they) that to have a backup, they need to be subscribed to a paid account.

So, change of plans, we should at least enable chrome.storage.sync as the main storage for new users and users that don't have more than 100KB or 512 templates. If they do, we should ask them to buy Gorgias (and move them to chrome.storage.local as it has a bigger limit).

**Comment by RomainLapeyre** [comment]
I think we should limit this to a few templates, say 10, so that it's doesn't eat sales

**Comment by rassom** [comment]
Any idea when this will be implemented? Thanks :-)

**Comment by xarg** [comment]
@rassom No timeline for this yet.

Please have a look at #157 for this.
