### ISSUE TITLE
Template not working with 4.0

### ISSUE THREAD

**Issue by RomainLapeyre** [gorgias/gorgias-chrome#150]
Gorgias is not working on Zendesk with 4.0

Reproduce: 
- Impersonate user id = 119 account's
- Go to Zendesk
- Try to type "ret", that doesn't expand into the full template

**Comment by RomainLapeyre** [comment]
Save issue for user id = 127 on this page:
https://www.dropbox.com/s/6vw3ep28zqob23i/Screenshot%202015-11-25%2007.50.30.png?dl=0

"It's a html with textarea tag
It worked perfectly until this morning"

**Comment by RomainLapeyre** [comment]
Note: my own templates work on Zendesk with 4.0

**Comment by RomainLapeyre** [comment]
Other website not working: MightyText

**Comment by xarg** [comment]
Should have been fixed in 4.0.3
