### ISSUE TITLE
Variables are not inserted where the cursor is

### ISSUE THREAD

**Issue by RomainLapeyre** [gorgias/gorgias-chrome#154]
Reproduce: 
1. Create a template with this text
   Hello ,

Thanks for reaching out,  unfortunately we just filled this position. Best of luck with your job search!
2. Insert a variable here: "Hello [HERE],"
--> The variable is inserted elsewhere.

**Comment by xarg** [comment]
I think this was fixed. Can't reproduce this anymore.
