### ISSUE TITLE
Don't add default templates back after they are deleted

### ISSUE THREAD

**Issue by RomainLapeyre** [gorgias/gorgias-chrome#155]
A customer is asking for the following: 
1. I delete default templates (hello)
2. I sync with Gorgias.io
3. I install the extension on another laptop, and login
   --> The "hello" template is back. The user doesn't want this.

**Comment by xarg** [comment]
It could be done by checking if the user is logged in on gorgias.io and not add them at all. The problem with this is that it's unlikely that they are logged in on a new computer. We can also delete them once the user is logged in, but are we sure that the user doesn't want them?

It's not super clear what to do here and I don't think it's super important for now.

**Comment by RomainLapeyre** [comment]
Yep agreed, just added that for tracking purposes. I think the best way to
go is probably to delete the templates after the user logs in for the first
time.

**Comment by xarg** [comment]
Closing this for now as it's not a common issue.
