### ISSUE TITLE
Firstname variable broken on LI profiles' messaging popin

### ISSUE THREAD

**Issue by RomainLapeyre** [gorgias/gorgias-chrome#156]
Reproduce: 
1. Go to a 1st degree connection page
2. Click "send message"
3. Insert a variable in the body
--> the variable is not populated

<img width="1328" alt="screenshot_2015-12-09_08_45_27_png" src="https://cloud.githubusercontent.com/assets/5151742/11688958/9c1d8f60-9e5d-11e5-9e76-985d1ca4815e.png">

**Comment by RomainLapeyre** [comment]
+1

**Comment by xarg** [comment]
I think LinkedIn changed their UI, is this still an issue?
