### ISSUE TITLE
Feature request: Mass mailing using a CSV

### ISSUE THREAD

**Issue by xarg** [gorgias/gorgias-chrome#158]
Feature request from @HappyTorso. We already have the template system working well. We could create a mass mailing feature that allows sending multiple emails using data from a CSV.

@RomainLapeyre what do you think about this, I know you're a fan of this too.

**Comment by RomainLapeyre** [comment]
That's a feature called "mail merge". Yesware, Streak and others have this. To me, it's more a CRM feature than a feature that a templating tool should have, so I don't think we should have it.

**Comment by xarg** [comment]
Agreed, closing this for now. Reopen if there is more interest here.
