### ISSUE TITLE
Support for tables

### ISSUE THREAD

**Issue by xarg** [gorgias/gorgias-chrome#159]
Seems quill.js (our template editor) doesn't support html tables at all. We will not have the support for tables until Quill adds them unfortunately. 

Related: https://github.com/quilljs/quill/issues/117

**Comment by LouisBarranqueiro** [comment]
+1

**Comment by jebarjonet** [comment]
+2

**Comment by xarg** [comment]
Since Quill is not moving here much let's try to find an alternative editor. @thomasgit123 will have a look at it.

**Comment by xarg** [comment]
Done in #265
