### ISSUE TITLE
gmail templates bug with 4.0.8

### ISSUE THREAD

**Issue by patrick-evolabs** [gorgias/gorgias-chrome#161]
On one of our machines, In Gmail, the Gorgias box does not generate the templates. We can still see them when clicking on the icon, but clicking one of them, or using *shortcut* + tab does not generate it.

Chrome version : 47.0.2526.106 (64-bit)
Operating system : OSX Yosimite 10.10.5
Console error message : 
Uncaught TypeError: Cannot read property 'split' of undefinedApp.plugin.getData 
@ content.js:3431setText 
@ content.js:1919(anonymous function) 
@ content.js:2086

UPDATE:
Actually, this problem exists on all of our machines now. Gorgias is just not working on chrome+gmail for us.

**Comment by xarg** [comment]
Hi @patrick-evolabs! 

Thanks for reporting this. And sorry about this. I traced down the problem to Gmail that changed their interface which broke the extension. It is fixed now in 4.0.9. I just published it so it will be available in 1h max.

You can force the update of the extension like so: Go to Chrome Extensions -> Enable Developer Mode -> Click on 'Update extensions now' - make sure you have Gorgias 4.0.9.

**Comment by patrick-evolabs** [comment]
Thanks,

Works again!
