### ISSUE TITLE
Templates not expanding in Zendesk

### ISSUE THREAD

**Issue by RomainLapeyre** [gorgias/gorgias-chrome#166]
Reproduce: 

1. Go to Zendesk (with the formatting option disabled: no markdown)
2. Open a ticket
3. Press "h" + TAB
4. Submit as internal note

--> the message is "h" and not "hello"

**Comment by RomainLapeyre** [comment]
Per our friends at Automatic.

**Comment by martinlatrille** [comment]
I can't manage to reproduce; works fine for me (public message or internal note). Do they have something specific ? Like specific settings, markdown-enabled editor maybe ?

**Comment by RomainLapeyre** [comment]
Still can't reproduce on gorgias.zendesk.com? For me the bug is still here :/

**Comment by RomainLapeyre** [comment]
Not an issue, most customers are switching to the Zendesk editor and don't experience the bug anymore.
