### ISSUE TITLE
Sort templates by alphabetical order

### ISSUE THREAD

**Issue by RomainLapeyre** [gorgias/gorgias-chrome#167]
+2

**Comment by RomainLapeyre** [comment]
+1

**Comment by xarg** [comment]
Add an option in the Options page that would add this functionality for both the template list and the template dialog in Gmail.

This option is disabled by default.

**Comment by xarg** [comment]
Fixed in version 5.6.21

**Comment by RomainLapeyre** [comment]
Several people are complaining that the search is not working anymore, I assume this is connected to this update.
