### ISSUE TITLE
Show more fields: Subject, To, CC, BCC

### ISSUE THREAD

**Issue by RomainLapeyre** [gorgias/gorgias-chrome#169]
Lots of customers asked us to add `CC`, `BCC` fields in the template.

We're thinking of adding a `Show more fields` link in the template.

When the link is clicked it should display these fields: `Subject`, `To`, `CC` and `BCC`.
When the fields have a value they should be displayed.
![a2e5cef0-a750-11e6-87c7-122a247f008d](https://cloud.githubusercontent.com/assets/5151742/20196788/28676f02-a751-11e6-8024-43084f197b12.png)

**Comment by RomainLapeyre** [comment]
+1

**Comment by RomainLapeyre** [comment]
+1

**Comment by xarg** [comment]
Someone requested a `To` field as well. I think that we might want to have something more generic with `To`, `CC` and `BCC`

**Comment by xarg** [comment]
+1 client left because we don't have it.
