### ISSUE TITLE
Import template is blocked

### ISSUE THREAD

**Issue by RomainLapeyre** [gorgias/gorgias-chrome#172]
Error message:

`background.js:167 POST https://gorgias.io/api/1/quicktexts/import 500 ()
(anonymous function) @ background.js:167p @ background.js:163g @ background.js:160(anonymous function) @ background.js:193n.$eval @ background.js:207n.$digest @ background.js:204n.$apply @ background.js:207(anonymous function) @ background.js:220e @ background.js:117(anonymous function) @ background.js:119`

Here's the file I had a bug with: https://drive.google.com/drive/u/0/folders/0B5qXV9POfdbQaUN3X1J2WVZOTWs

**Comment by xarg** [comment]
Fixed server side
