### ISSUE TITLE
Autocomplete dialog bug in Zendesk

### ISSUE THREAD

**Issue by RomainLapeyre** [gorgias/gorgias-chrome#176]
Reproduce: 
- Make sure you have the WYSIWYG editor enabled in Zendesk
- Go to a ticket
- Press CTRL+TAB
- Insert a template

---> the template is inserted before the response area

![image](https://cloud.githubusercontent.com/assets/5151742/14501408/9b0e29e8-01a6-11e6-99ea-c592fd93a59b.png)

**Comment by RomainLapeyre** [comment]
A large customer (100+ users) is having this issue, we need to fix it. @xarg, can we ask Ionut?

**Comment by RomainLapeyre** [comment]
UPDATE: Asked customer to use a workaround before we fix it.

**Comment by xarg** [comment]
@RomainLapeyre is the workaround changing the keyboard shortcut?

**Comment by RomainLapeyre** [comment]
Yes.

**Comment by xarg** [comment]
I think this is safe to close for now right?
