### ISSUE TITLE
Extension is not loading the user profile

### ISSUE THREAD

**Issue by RomainLapeyre** [gorgias/gorgias-chrome#189]
The extension is stuck, the user can't insert any template. 

![img_0335](https://cloud.githubusercontent.com/assets/5151742/15400727/d5659178-1dec-11e6-8a71-577a0825e293.jpg)

**Comment by xarg** [comment]
Does refresh fix it?

**Comment by RomainLapeyre** [comment]
Let me double check that.

**Comment by RomainLapeyre** [comment]
Yes, let's not fix for now.
