### ISSUE TITLE
Can't insert templates on delegated inboxes on Gmail

### ISSUE THREAD

**Issue by RomainLapeyre** [gorgias/gorgias-chrome#194]
Reproduce:
- Go to a delegated inbox
- Try to insert a template
--> nothings happens

Error message:
chrome-extension://lmcngpkjkplipamgflhioabnhnopeabf/content/js/content.js:3445 Uncaught TypeError: Cannot read property 'innerHTML' of null
VM2161:121 Unknown view type

Seems Gmail changed their code

**Comment by xarg** [comment]
Fixed in 5.1.7 (in chrome store).
