### ISSUE TITLE
Quick access button is showing the full tempalte

### ISSUE THREAD

**Issue by RomainLapeyre** [gorgias/gorgias-chrome#196]
Reproduce: 
- Make sure you have template `caee6cb7-06e9-4fca-bad0-e0bc68225283` in your account
- Click the quick access button

--> the quick access button shows the body of the template as its title
<img width="240" alt="boite_de_reception_-_romain_lapeyre_hec_edu_-_messagerie_hec_paris" src="https://cloud.githubusercontent.com/assets/5151742/15851087/a52c810c-2c9b-11e6-8d69-9355a264f699.png">

**Comment by xarg** [comment]
Fixed in 5.3.1
