### ISSUE TITLE
Can't update sharing for a large number of templates

### ISSUE THREAD

**Issue by RomainLapeyre** [gorgias/gorgias-chrome#200]
Issue with 2 large customers:
- Some templates are marked as "shared with everyone", but in reality, they are not shared with all the users. 
Ex: `UK Important Departure & Arrival Information` is shared with all. Though, the test user_id = 1148 can't see it.
- Some templates were created as "shared with everyone". Though, after a bit of time, they are shared only with specific people, and marked as such "shared with specific people". 
- When you try to fix it, and select all the shared templates to set their sharing to "shared with all", it's not affecting all templates. Some templates, even if they were selected while using the bulk action to update sharing, are still shared with " specific people"
Examples: see #support channel on Slack, or ask @RomainLapeyre

Expected behavior: 
- Select all shared templates for user_id 325
- Use bulk actions to set the sharing as "shared with everyone", and have all the templates shared with everyone.

Related ticket: https://gorgias.gorgias.io/app/ticket/40279

**Comment by RomainLapeyre** [comment]
@xarg another large customer is having this issue, this is an important bug.

**Comment by xarg** [comment]
@RomainLapeyre I think I fixed this, can you give it another try?

**Comment by RomainLapeyre** [comment]
It's working fine
