### ISSUE TITLE
Buggy bulk delete

### ISSUE THREAD

**Issue by jebarjonet** [gorgias/gorgias-chrome#210]
The bulk delete (selecting multiple templates then pressing `Delete`) does not work correctly and display a wrong confirmation message : 

Example : 
- Delete the template "Hello"
- Select with bulk the template "World"
- Press `Delete`
- The confirmation message says "Are you sure you want to delete "Hello" template ?" (the previously deleted template)

**Comment by ghinda** [comment]
I can't replicate this. Can you test again with the latest `master`?

It could be that it was fixed by the the `ListCtrl` refactoring https://github.com/gorgias/gorgias-chrome/commit/f764b1c774b793ba66690b65d9f28809fb3ba9e6.
