### ISSUE TITLE
Change date locale in template ???

### ISSUE THREAD

**Issue by amonsat** [gorgias/gorgias-chrome#211]
How i can change date locale in template ???
in moment we can change it.
be greet if we can like this {{date '-1' 'days' 'dddd' 'fr'}}:

**Comment by xarg** [comment]
Closing this as there is no response for quite some time.

**Comment by fabien-corail** [comment]
Hi, any update on this ? I'd love to be able to have the date in the desired language.

**Comment by ghinda** [comment]
We are planning this as part of https://github.com/gorgias/gorgias-chrome/issues/364.
It should be available sometime in the next month or so.
