### ISSUE TITLE
Template inserted multiple times

### ISSUE THREAD

**Issue by RomainLapeyre** [gorgias/gorgias-chrome#212]
## Description

When you're on Zendesk and insert a note in the sidebar note widget, the template is inserted multiple times. 
See this [gif](https://drive.google.com/a/gorgias.io/file/d/0B5qXV9POfdbQMzExcS1sUkpFejQ/view?usp=sharing) from a customer. 
## Step to reproduce
- Add the `User Data` app in Zendesk
- Open a ticket
- Insert a template in the note section of the user data widget

--> It's inserted multiple times
<img width="470" alt="gorgias_-_agent" src="https://cloud.githubusercontent.com/assets/5151742/19741348/2da47c72-9b75-11e6-852b-79b102ff5b44.png">

**Comment by martinlatrille** [comment]
For me, it's always inserted exactly 5 times

**Comment by RomainLapeyre** [comment]
Yes that's related to their rebranding, it started happening on Wednesday. Lots of people have this issue.
