### ISSUE TITLE
Private templates are public by default

### ISSUE THREAD

**Issue by RomainLapeyre** [gorgias/gorgias-chrome#213]
## Reproduce
- Log in to a paid account in Gorgias
- Create a private template

--> The template shows up in public templates, and not private. 
You have to manually change the sharing to private in order to stop sharing it with everyone.

**Comment by ghinda** [comment]
This is caused by the `Share templates by default with all your team.` setting in `Settings > My Account`. 

This is set to `True` for all new accounts. Do we want to set it to 'False' for new accounts?

**Comment by RomainLapeyre** [comment]
If we remove it, when users create templates from the "all" tab, they will be private by default, which is not the default behavior users expect. 

I think we need to change the scope of this option, to only apply to templates that are created from the `all` tab. Templates created from the `private` tab should be private by default all the time, and those created in the `shared` tab should be shared by default all the time too.
