### ISSUE TITLE
Tab is just simply bringing me to next button in inbox/gmail

### ISSUE THREAD

**Issue by mikecreuzer** [gorgias/gorgias-chrome#225]
I cannot get the tab character to load template. It used to work fine and lately has not, even with defaults set.

**Comment by xarg** [comment]
@mikecreuzer that is strange, are you sure you haven't changed the Keyboard shortcut trigger key in the settings? Maybe another extension interfering?

**Comment by xarg** [comment]
Seems to have been fixed in support.
