### ISSUE TITLE
Wrong explanation of "Subject" field tooltip

### ISSUE THREAD

**Issue by LouisBarranqueiro** [gorgias/gorgias-chrome#227]
#### Description:
- Tooltip of `subject` field say that the subject will be replaced, this is not the case: subject is appended.

Step to reproduce the bug:
- create new template
- hover subject field

**Comment by xarg** [comment]
This is intentional, it's not a bug. Who reported this?

**Comment by LouisBarranqueiro** [comment]
Ok, so we need to change tooltip text because it said that the subject will be replaced.
<img width="426" alt="screen shot 2017-01-12 at 3 43 44 pm" src="https://cloud.githubusercontent.com/assets/4705626/21894016/f109cf32-d8dd-11e6-8baa-72cf2178251c.png">
