### ISSUE TITLE
Support of new Linkedin version

### ISSUE THREAD

**Issue by jebarjonet** [gorgias/gorgias-chrome#229]
Linkedin just released a new version of the website. The extension currently does not work on this new version.

**Comment by RomainLapeyre** [comment]
I tested here, it works: 

![image](https://cloud.githubusercontent.com/assets/5151742/21991311/ea91c5ec-dbc6-11e6-96c4-b1c607ab2677.png)

It there a newer version of Linkedin messenger than this one? If no, is the customer using linkedin pro? 

For now, 2ppl have requested it (=$10/m), to the ROI is low.

**Comment by jebarjonet** [comment]
There is a newer version, this is not the newer. The newer looks like this: 

<img width="494" alt="screen shot 2017-01-16 at 10 35 38" src="https://cloud.githubusercontent.com/assets/4401230/21995040/9c7a29e2-dbd7-11e6-9798-5c5a652f326a.png">

This new version is progressively deployed, not everybody has it at the same time apparently.

**Comment by xarg** [comment]
I'm putting this on hold until LinkedIn is more stable and we have more people complaining about it. For now our official response is this: 

> We don't support LinkedIn at the moment because of all their recent changes and we're waiting for it's more stable. We do not support or intend to support LinkedIn Recruiter, patches are welcome though.

**Comment by martinlatrille** [comment]
+1 for LinkedIn new version
