### ISSUE TITLE
Improve first name and last name detection

### ISSUE THREAD

**Issue by jebarjonet** [gorgias/gorgias-chrome#236]
> If I'm emailing "Barack Obama", then the `{{to.first_name}}` tag works great ("Barack")
> But if I'm emailing "Obama, Barack", then `{{to.first_name}}` tag doesn't work ("Obama,")

Some services that display users by their family name first would set the full name with the format `Last_name, First_name`. The extension could maybe detect if there is a `,` in the full name, split on it, and set the first name as the second member and the last name as the first member.

**Comment by xarg** [comment]
@ghinda the first name/last name detection is very flaky recently on Gmail. Some people are complaining more and more about it. 

I propose adding 2 new fields in the Settings with first and last name with the fallback to what we have today if they are not set. Should be an easy fix can you look into it when you have the time?

Thanks!
