### ISSUE TITLE
Add more payment data to comply with VAT rules

### ISSUE THREAD

**Issue by RomainLapeyre** [gorgias/gorgias-chrome#237]
## Why we need it
Quaderno invoices need to be manually updated for EU VAT MOSS compliance. 

## What we need
Send the billing country and IP address (we can retrieve the bank country by checking the customer's credit) as a metadata inside the Stripe customer

Tutorial here: 
http://support.quaderno.io/article/16-customising-your-stripe-integration

**Comment by RomainLapeyre** [comment]
@ramsgoli are you available to work on this. This is pretty important for us as it generates a lot of manual work. Thanks!

**Comment by ramsgoli** [comment]
@RomainLapeyre created a [PR](https://github.com/gorgias/gorgias.io/pull/83) over in the website source repository that should fix this

**Comment by RomainLapeyre** [comment]
Thanks!

**Comment by xarg** [comment]
Closing this since it's a backend issue.
