### ISSUE TITLE
Create account invitation not sent

### ISSUE THREAD

**Issue by RomainLapeyre** [gorgias/gorgias-chrome#239]
## Description
katie@packhealth.com, alison@packhealth.com and bree@packhealth.com were invited to create an account. They never got the invite email. There's [no email log](https://mailgun.com/app/logs/gorgias.io?keyword=packhealth.com) in Mailgun.

## Reproduce
- Add a new user to our account
--> you don't get the invite email

**Comment by xarg** [comment]
Was an issue with the worker

**Comment by RomainLapeyre** [comment]
This happened again to margot@wttj.co and all her team. 

There is no invitation email in the [Mailgun logs](https://app.mailgun.com/app/logs/gorgias.io?sort=datetime%3Adesc&variant=FD939_base&testId=FD-939&date_from=2018-11-21T00%3A00%3A00.000Z&date_to=2018-11-27T23%3A59%3A59.999Z&skip=0&search=margot%40wttj.co)
