### ISSUE TITLE
{{from.last_name}} doesn't work

### ISSUE THREAD

**Issue by RomainLapeyre** [gorgias/gorgias-chrome#251]
When you use the `{{from.last_name}}` or the `{{from.name}}` variable, it prints `Google+ Profile–Privacy`, instead of the last name / full name of the user. 

It's probably linked to an update in Gmail's dom. 
![image](https://cloud.githubusercontent.com/assets/5151742/24714053/361c461a-19dc-11e7-8cf7-81e83e9d6ce3.png)

**Comment by xarg** [comment]
@ghinda make sure it works with other languages than english as well. Gmail translates the titles so it's not a good idea to base our code on them.

**Comment by xarg** [comment]
Fixed in 5.6.7
