### ISSUE TITLE
Limit matched sites

### ISSUE THREAD

**Issue by jhult** [gorgias/gorgias-chrome#266]
Right now, the extension is allowed on all domains (which seems unnecessary).

Can we limit the extension to the supported sites (Gmail, Outlook.com, Yahoo Mail, Linkedin)?

I think this should be as simple as updating the [manifest](https://github.com/gorgias/gorgias-chrome/blob/master/src/manifest.json).

**Comment by xarg** [comment]
Hello, we have a lot of customers that use Gorgias on their intranet websites so it would be impossible to list all of them.

I'm not a big fan of this either, in fact when we first started we did only the websites you enumerated and when added a few more people just clicked on 'deny' when asked for new permissions disabling our extension entirely - and generated massive support for us. 

Unless Chrome fixes this then the answer is a strong no from us and I suspect that's the attitude of the majority of the chrome extension devs.

Thanks for understanding.
