### ISSUE TITLE
Choice accents

### ISSUE THREAD

**Issue by xarg** [gorgias/gorgias-chrome#274]
Variables and templates documentation: https://docs.gorgias.io/chrome-extension/templates#list_of_variables

Customer message:

> when I use the `choice` variable with phrases containing accented letters it outputs the following:
> 
> `&ocirc;`
> `&ograve;`
>`&ocirc;`
> `&oacute;`
> `&oacute;`
> `&ograve;`
> 
> I tested this with plenty of accented letters: 
> {{choice 'é, è, ê, õ, ô, ó, ò, â, ã, á, à,'}}

**Comment by xarg** [comment]
Closing for now - the usage of choices are low - reopen if people complain.

**Comment by ghinda** [comment]
Now fixed with the latest version of the editor in the dashboard. 
We're now using `entity_encoding: 'raw'` for `tinymce`, so special characters are preserved.
