### ISSUE TITLE
[Feature Request] Amend Subject and Include Original attachemnts

### ISSUE THREAD

**Issue by ofir-bar** [gorgias/gorgias-chrome#278]
Hi all, please add the following 2 features:

Amend the email subject without replacing it entirely. for example, if the existing subject is:

Company Ticket #55521111 // Helping Customer Ticket example

To: (notice the "[URGENT]" )
[URGENT] Company Ticket #55521111 // Helping Customer Ticket example

Feature 2:

Include original attachments. when customers send us files and we want to add another office to the email chain but also include the files we got, we need to manually include the original attachments and it happens all the time.

**Comment by xarg** [comment]
Thanks for the suggestions, but we're not going to implement them.
