### ISSUE TITLE
Reset password emails not being sent

### ISSUE THREAD

**Issue by RomainLapeyre** [gorgias/gorgias-chrome#288]
Welcome to the jungle tried to reset the password of `guillaume.sicot@wttj.co` without success. 

[No email is being sent](https://app.mailgun.com/app/logs/gorgias.io?date_from=2018-11-21T00%3A00%3A00.000Z&date_to=2018-11-27T23%3A59%3A59.999Z&search=guillaume.sicot%40wttj.co&sort=datetime%3Adesc) on Mailgun

**Comment by ghinda** [comment]
Seems to work now.
