### ISSUE TITLE
Too many fields for quicktext

### ISSUE THREAD

**Issue by bumbu** [gorgias/gorgias-chrome#31]
The field which is bothering me is _Subject_. It gets me confused.

Right now there are these fields available:

* Title - denotes heading (probably we can get rid even of these one)
* Subject - confusing
* Shortcut - useful thing
* Tags
* Quicktext - useful thing

I propose first to get rid of subject.
Then there are few ways to simplify the fields:

* Remove shortcut and search autocompletion by the title (searching matches not only at the beginning of word but in whole phrase)
* Moving tags into title (same as #8)
* Remove shortcut and move tags into title (join 2 previous tasks)

In a really minimalistic way we can stay only with Subject and Quicktext.

**Comment by xarg** [comment]
Fixed in 2.0.4
