### ISSUE TITLE
This extension may have been corrupted - Templates lost

### ISSUE THREAD

**Issue by mondalaci** [gorgias/gorgias-chrome#315]
Gorgias worked like a charm up until 6.2.2 at which point I saw the "This extension may have been corrupted" message on the extension page. I clicked the Repair button, then it upgraded to 6.2.3 and all of my templates were gone.

Any way to restore my templates? I backed up my google-chrome directory on Linux recently, but whenever I restore Default/Extensions/lmcngpkjkplipamgflhioabnhnopeabf/6.3.2_0, the above scenario repeats itself, and I end up with no templates. I can export the CSV from my previous installation, but can't import it back.

**Comment by ghinda** [comment]
There is a known issue with Chrome `76` randomly corrupting extensions:
https://crbug.com/982001
https://crbug.com/977805

It was reported initially on the Beta channel but it seems to have persisted on `76 Stable` as well.
Other extension authors are reporting the same issue, so it shouldn't be related to the update to Gorgias Templates.

Do any of your other extensions get corrupted?
To be safe, the best approach would be to sign-up for a paid subscription so we can back-up your templates.

**Comment by mondalaci** [comment]
None of my other extensions have been corrupted yet. Thanks for the heads-up! I'll consider subscribing.
