### ISSUE TITLE
Make the Show more fields button look clickable

### ISSUE THREAD

**Issue by ghinda** [gorgias/gorgias-chrome#337]
Make the "Show more fields" button look like a link, or a button, so that it looks clickable.
Right now it only looks like a link (blue, underlined) when hovered.

![show-more-fields](https://user-images.githubusercontent.com/325171/70210629-cbec6d00-173b-11ea-8862-e0b2909ac15f.png)

**Comment by xarg** [comment]
let's add a chevron like this: `Show more fields ⌄`
