### ISSUE TITLE
Cannot attach more than 1MB

### ISSUE THREAD

**Issue by xarg** [gorgias/gorgias-chrome#353]
Currently there is a limit 1MB for the attachment size which limits the type of attachments we can make. Would be great, at least for the paying users to be able to attach more: 10MB would be great, 100MB even better.

**Comment by ghinda** [comment]
The attachment file size upload limit is now `3MB`. We can increase it further if any customers ask for it.

After we release free accounts, we can have separate limits depending on subscription.

**Comment by xarg** [comment]
Let's see if people complain and we'll change it if needed.
