### ISSUE TITLE
Loom Chrome extension breaks template insert

### ISSUE THREAD

**Issue by sprankhub** [gorgias/gorgias-chrome#355]
We use the Gorgias Chrome extension together with JIRA Service Desk since years and we really love it!

JIRA just rolled out there new [issue view containing the new Atlassian editor](https://support.atlassian.com/jira-core-cloud/docs/what-is-the-new-jira-issue-view/) to JIRA Service Desk and unfortunately, this breaks Gorgias. There is an error in the console when trying to use a shortcut:

    Uncaught (in promise) TypeError: Cannot read property 'nodeType' of undefined
        at k (content.js:34)
        at content.js:34
        at content.js:34

I know that you do not officially support JSD, but would you mind checking anyway?

**Comment by ghinda** [comment]
Thanks for letting us know about the issue!
I did a quick test on the JIRA Issue View, but everything seems to work as expected. I tested the Description and Comment editors in the Issue view.

Does it look different on your end?
![jira-issue-view](https://user-images.githubusercontent.com/325171/73752201-28363200-4769-11ea-864c-ffc409cd5dc9.png)

**Comment by sprankhub** [comment]
Thanks for checking @ghinda! It looks similar, but a bit different, because it is a JIRA Service Desk project:

![image](https://user-images.githubusercontent.com/930199/73758005-59fbc880-476a-11ea-8a7c-e0ecbb037a02.png)

Do you have a chance to check it there as well? If not, any idea how I can help you debug the issue?

**Comment by ghinda** [comment]
Just tried the Demo Service Desk and it seems to work there as well:
![customer-reply](https://user-images.githubusercontent.com/325171/73759380-8fa5af00-4774-11ea-89cc-d98a226596ae.png)

Could there be something wrong with the specific template you're trying to insert? Or are you seeing the same error with any template?

**Comment by sprankhub** [comment]
I have that issue with any template. Even if I click CTRL + Space and manually select a template, the same issue occurs... I tried disabling extensions and found out that this is a compatibility issue with [Loom](https://chrome.google.com/webstore/detail/loom-video-recorder-scree/liecbddmkiiihnedobmlmillhodjkdmb). If I disable Loom, it works again. Can you reproduce it with Loom installed?

**Comment by sprankhub** [comment]
Could you additionally try a template with two lines like the following?

    Test1
    Test2

In my case, this is inserted as

    Test1 Test2

**Comment by ghinda** [comment]
I managed to reproduce it, the Loom extension is the one causing the issue with the `nodeType` error. I'll take a look to see exactly what's causing it.

For the issue with the newlines, can you please open a separate issue so we can track it there?

**Comment by sprankhub** [comment]
See #356 regarding the new line bug. I do not really use Loom anyway and uninstalled it, so up to you if you want to fix that :)
