### ISSUE TITLE
New Line Issue In New JIRA Issue View / Atlassian Editor

### ISSUE THREAD

**Issue by sprankhub** [gorgias/gorgias-chrome#356]
I have a template, which looks like the following:

    Test1
    Test2

The default WYSIWYG editor produces the following HTML from it:

    <div>Test1</div>
    <div>Test2</div>

In the new Atlassian editor, this is inserted as

    Test1 Test2

Even if I use `p` tags, it does not work.

Could you ensure that new lines are preserved?

**Comment by ghinda** [comment]
We just released a fix for the issue. The new version is in review on the Chrome Web Store right now.
Once you get the latest update `6.6.2`, newlines should be working as expected in the new JIRA editor.

**Comment by sprankhub** [comment]
Thank you so much for the quick fix! Works!
