### ISSUE TITLE
Parametric templates

### ISSUE THREAD

**Issue by mondalaci** [gorgias/gorgias-chrome#369]
Parameters would be very useful in some scenarios. Let's say I have a knowledgebase template with the text shortcut `kb`. Then I would be able to type `kb:shipping`. Within the template `{{1}}` would be replaced with `shipping`.

**Comment by ghinda** [comment]
Thanks for the suggestion! Could you give us a short example of what a template would look like? Just to get a clear idea of the use case.

We allow the `:` character in template shortcuts right now, so it could get tricky for backwards compatibility.

**Comment by mondalaci** [comment]
The template is:

> Hi {{to.first_name}},
> 
> Please see the following knowledgebase query, and let me know if you have further questions which are not featured in the knowledgebase.
> 
> https://ultimatehackingkeyboard.com/knowledgebase?q={{1}}
> 
> Cheers!

Instead of the proposed template parameter syntax, here's an alternative syntax: `kb(shipping)`

**Comment by xarg** [comment]
Could also work using a cursor position like described here: https://github.com/gorgias/gorgias-chrome/issues/22

Probably easier to use when you need to fill in multiple vars.

**Comment by mondalaci** [comment]
Yes, that'd be excellent. I'm wondering how to make the cursor position feature for multiple arguments, though.

**Comment by ghinda** [comment]
With multiple cursors, as described here https://github.com/gorgias/gorgias-chrome/issues/22#issuecomment-51622331, you'd just have to press Tab after filling in the first cursor/form-like-field. 

With the "multiple cursors" feature you'd still type the same number of keys eventually.

@mondalaci Do you think this would solve your use-case? If it does, I'm going to merge this into #22.

**Comment by mondalaci** [comment]
Yes, definitely! I'd actually much prefer to use the "multiple cursors" feature. Very excited about this one!

Feel free to merge this issue.

**Comment by ghinda** [comment]
Closing as merged into #22
