### ISSUE TITLE
Make it possible to remove the G button from Gmail composer

### ISSUE THREAD

**Issue by mondalaci** [gorgias/gorgias-chrome#397]
The G button is always present in the top right corner of the Gmail composer area which is sometimes quite disturbing as it covers text that I cannot read.

Given that I always use shortcuts, I don't need this button at all, and I'd love to be able to disable it.

**Comment by ghinda** [comment]
You can disable the G button from Gmail from `Settings -> Enable Quick Access button`.
![quick-access](https://user-images.githubusercontent.com/325171/87404694-2483c280-c5c7-11ea-8f2d-c85fef393227.png)

**Comment by mondalaci** [comment]
Geez, sorry for not noticing it! Keep up the great work!
