### ISSUE TITLE
Dialog searching better by tags

### ISSUE THREAD

**Issue by xarg** [gorgias/gorgias-chrome#86]
Searching by tags is rather difficult in the dialog. I think we should add the possibility to search by tags in the dialog directly. The problem is how exactly to solve this UI wise.

**Comment by RomainLapeyre** [comment]
+1 from customer

**Comment by xarg** [comment]
Solution to this could be a Gmail like syntax in search. Something like:

```
in: sales <Search String> 
```

Another way to do this would be to display tags as folders so by default you would see the list of tags, then when you click on tag it shows you the list of the templates in that tag (similar to what Zendesk does today with macros).

**Comment by RomainLapeyre** [comment]
+1 from a paying customer

**Comment by jebarjonet** [comment]
+3 this week
