### ISSUE TITLE
Non-contenteditable fields bugs

### ISSUE THREAD

**Issue by xarg** [gorgias/gorgias-chrome#88]
In a textarea we you use the Hello template the range selection goes at the end of the text.

Inserting a template via the dialog removes the word that it's next to.

**Comment by ghinda** [comment]
Fixed in #96.

The fix for not deleting the selected `word` seems to also fix the range selection issue.

**Comment by xarg** [comment]
The selection after insertion is still off for some reason:

https://www.youtube.com/watch?v=tJoN769tXU8
