### ISSUE TITLE
TAB Functionality Broken When Focus on Sender Dropdown

### ISSUE THREAD

**Issue by sprankhub** [gorgias/gorgias-chrome#91]
I am using Chromium Version 39.0.2171.65 Ubuntu 14.04 (64-bit) with Gorgias 1.6. When I compose a new message, add a recipient and press TAB, the focus is on the sender dropdown. If I click TAB once more in order to jump into the text area so that I can write my mail, nothing happens. If I disable Gorgias, everything works as expected (= the focus jumps into the text area and I can write).

Kind of annoying. Do you know that issue? Can you reproduce and fix it? Thanks in advance! :-)

**Comment by xarg** [comment]
Is this on Gmail? I can't reproduce this on Chrome 40.0.2214.91 on OSX. I'm updating Ubuntu now to make sure. If it's not too much to ask, could you make a video capture of the issue?

This software seems to be nice: http://www.howtogeek.com/howto/24742/record-screen-activity-in-ubuntu-with-recordmydesktop/

**Comment by xarg** [comment]
Tested on Chromium 34 on Ubuntu. Seems to be working as expected. It takes a long time to update...

**Comment by sprankhub** [comment]
This is on Gmail, yeah. Screencast is a lot of work :/ If you like, we can do a Teamviewer session. But maybe you can reproduce it after the update is completed...

**Comment by xarg** [comment]
I was able to reproduce it now. I'll try to figure out what's happening.

**Comment by sprankhub** [comment]
Could not test it yet, but thank you very much!

**Comment by xarg** [comment]
Thanks for reporting it :+1: 

I just pushed it on the Webstore. You should get the update momentarily (1h max). The new version is 1.6.1
