### ISSUE TITLE
Improve Wizard

### ISSUE THREAD

**Issue by xarg** [gorgias/gorgias-chrome#92]
- [ ] Do another version of the demo with sequential instructions on how to use the extension. The idea is to 'force' the user to complete one step after the other to make her understand how it works.
- [ ] Add Spanish?
- [ ] Move 'Closing lines' after the 'Greetings'
- [ ] Show all templates for the selected languages.
- [ ] Remove a few categories that are used less often according to mixpanel

**Comment by RomainLapeyre** [comment]
![step 1](https://cloud.githubusercontent.com/assets/5151742/6276537/e5decb3a-b887-11e4-9418-63cea88c0212.png)
![step 2](https://cloud.githubusercontent.com/assets/5151742/6276538/e5fc83f0-b887-11e4-89ad-eccc30cd9b72.png)
![step 3](https://cloud.githubusercontent.com/assets/5151742/6276539/e60337ae-b887-11e4-8e9c-b15fc302fe08.png)
![step 4](https://cloud.githubusercontent.com/assets/5151742/6276540/e60537c0-b887-11e4-8564-fcbd18763bbc.png)
Step 5: choose your language
Step 6: add some templates
![step 7](https://cloud.githubusercontent.com/assets/5151742/6276688/ea628e2a-b888-11e4-926b-7d90f59d9de0.png)

**Comment by RomainLapeyre** [comment]
Alex, I've added the screenshots of the wizard in the github issue. I've tested it with a few people and I think it will perform better than the current one. My only concern is the number of steps (7). Let me know what you think. The sooner we can work on this, the better. I had today the same feedback as I already had: some people didn't get how to use Gorgias.
